import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import Toolbar from "@mui/material/Toolbar";
import Logo from "./../assets/logo.jpg";
import Input from "@mui/material/Input";
import InputLabel from "@mui/material/InputLabel";
import InputAdornment from "@mui/material/InputAdornment";
import FormControl from "@mui/material/FormControl";
import TextField from "@mui/material/TextField";
import SearchIcon from "@mui/icons-material/Search";
import Markdown from "react-markdown";
import Tabs from "@mui/material/Tabs";
import Tab from "@mui/material/Tab";

export default function Home() {
  const markdown = "###### Hi, *This is markdown file*!";
  const menuList = [
    {
      name: "tab-a",
      id: "a",
      child: [
        { name: "tab-a-1", id: "a-1", child: [] },
        { name: "tab-a-2", id: "a-2", child: [] },
        { name: "tab-a-3", id: "a-3", child: [] },
        { name: "tab-a-4", id: "a-4", child: [] }
      ]
    },
    {
      name: "tab-b",
      id: "b",
      child: [
        { name: "tab-b-1", id: "b-1", child: [] },
        { name: "tab-b-2", id: "b-2", child: [] },
        { name: "tab-b-3", id: "b-3", child: [] },
        { name: "tab-b-4", id: "b-4", child: [] }
      ]
    },
    {
      name: "tab-c",
      id: "c",
      child: [
        { name: "tab-c-1", id: "c-1", child: [] },
        { name: "tab-c-2", id: "c-2", child: [] },
        { name: "tab-c-3", id: "c-3", child: [] },
        { name: "tab-c-4", id: "c-4", child: [] }
      ]
    },
    {
      name: "tab-d",
      id: "d",
      child: [
        { name: "tab-d-1", id: "d-1", child: [] },
        { name: "tab-d-2", id: "d-2", child: [] },
        { name: "tab-d-3", id: "d-3", child: [] },
        { name: "tab-d-4", id: "d-4", child: [] }
      ]
    }
  ];
  const [subMenu, setSubMenu] = useState([]);
  const [value, setValue] = useState("one");
  const [subValue, setSubValue] = useState("");

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };

  console.log(subMenu);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="content">
        <Box className="bar-content">
          <Toolbar className="styled-tool-bar">
            <Box className="logo-box">
              <Image width={48} height={48} src={Logo} />
              Website Name
            </Box>
            <Box className="search-box">
              <TextField
                id="search-input"
                size="small"
                placeholder="Please Enter Something..."
                InputProps={{
                  startAdornment: <SearchIcon />
                }}
              />
              <Button color="inherit">Login</Button>
            </Box>
          </Toolbar>
        </Box>
        <Box className="middle-content">
          <Box sx={{ width: "100%" }} className="menu-content">
            <Tabs value={value}>
              {menuList?.map((item) => (
                <Tab
                  value={item?.id}
                  label={item?.name}
                  onClick={() => {
                    setValue(item?.id);
                    setSubMenu(item?.child);
                  }}
                />
              ))}
            </Tabs>
          </Box>
          {subMenu?.length > 0 && (
            <Box sx={{ width: "100%" }} className="menu-content">
              <Tabs value={subValue}>
                {subMenu?.map((item) => (
                  <Tab
                    value={item?.id}
                    label={item?.name}
                    onClick={() => {
                      setSubValue(item?.id);
                      console.log("do something");
                    }}
                  />
                ))}
              </Tabs>
            </Box>
          )}
          <Box className="artical-content">
            <Markdown className="scroll-content">{markdown}</Markdown>
          </Box>
        </Box>
        <Box className="logo-box">
          <Image width={48} height={48} src={Logo} />
          Website Name
        </Box>
      </Box>
    </>
  );
}
