import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import Button from "../../components/Button";
const inter = Inter({ subsets: ["latin"] });



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const components = {
  button:Button
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*网页头部份*/}
        <header className="bg-gray-800 py-4 ">
          <div className="container flex justify-between px-8 w-full max-w-full">
            <div className="logo text-white flex justify-between items-center w-60">
               <Image
                 className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
                 src="/vercel.svg"
                  alt="Next.js Logo"
                 width={100}
                 height={37}
                 priority
              />
              <div>Next.js Demo</div>
            </div>

            <div className="right-area flex items-center ">
              <form className="search-form mr-4">
                <input type="text" placeholder="请输入搜索信息" className="px-3 py-1 rounded bg-gray-700 text-white" />
                <button type="submit" className="px-4 py-1 bg-gray-600 rounded text-white ml-2" >搜索</button>
              </form>
              <button className="login-button px-4 py-1 bg-blue-500 rounded text-white ">登录</button>
              <nav className="navigation ml-4">
              </nav>
            </div>
          </div>
        </header>
        {/*网页内容部份*/}
        <div className="h-screen flex ">
          <nav className="main-menu bg-gray-800 text-white w-64 py-4 px-8 h-screen">
            <div className="container mx-auto text-white">
              <ul className="mt-1">
                <li className='mb-2'><Link href="/" >首页</Link></li>
                <li className="mr-6">
                  <Link href="/menu1" className="">菜单1</Link>
                  <ul className="sub-menu px-3 mt-2">
                    <li className="mt-2"><Link href="/menu1/submenu1" >我是子菜单1</Link></li>
                    <li className="mt-2"><Link href="/menu1/submenu2" >我是子菜单2</Link></li>
                  </ul>
                </li>
                <li className="mr-6 mt-3"><Link href="/menu2" className="">菜单2</Link></li>
                <li className="mr-6 mt-3"><Link href="/menu3" className="">菜单3</Link></li>
                <li className="mr-6 mt-3"><Link href="/my-mdx-page" className="">markdown</Link></li>
              </ul>
            </div>
          </nav>
          <main className="bg-slate-500 px-8 py-8 w-full">
            {children}
          </main>
        </div>
        {/*网页页脚部份*/}
        <footer className="bg-gray-800 py-4 mx-auto">
          <div className=" w-60 my-0 mx-auto text-white flex text-center">
            <Image
              className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
              src="/vercel.svg"
              alt="Next.js Logo"
              width={50}
              height={27}
              priority
            />
            <span className="ml-2">Next.js Demo</span>
          </div>
        </footer>
      </body>
    </html>
  );
}
